server:
  port: 9000

spring:
  application:
    name: running
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql-545250.user-arthurbulle:5432/defaultdb
    username: user-arthurbulle
    password: 2er5fus2x8nw6n6ojuoa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level) %clr(%-36logger{36}){cyan} %msg%n"
  level:
    root: ERROR
    fr:
      ensai: DEBUG
    org:
      springframework:
        boot:
          web:
            embedded:
              tomcat: INFO
        data:
          repository:
            CrudRepository: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
